import { isBlacklisted } from './lib/blacklist.js';
export const mbtis={INTJ:['建筑师','烧脑悬疑、科幻、犯罪推理',['悬疑','科幻','犯罪']],INTP:['逻辑学家','科幻、硬核悬疑、纪录片',['科幻','悬疑','纪录片']],ENTJ:['指挥官','商战、战争史诗、大男主爽片',['商战','战争','动作']],ENTP:['辩论家','黑色幽默、讽刺喜剧、脑洞奇幻',['喜剧','讽刺','奇幻']],INFJ:['提倡者','文艺剧情、治愈系、心理片',['文艺','治愈','心理']],INFP:['调停者','奇幻、童话、治愈系、青春片',['奇幻','治愈','青春']],ENFJ:['主人公','励志、群像剧情、家庭温情',['励志','剧情','家庭']],ENFP:['竞选者','奇幻冒险、公路片、欢乐喜剧',['奇幻','冒险','旅行','喜剧']],ISTJ:['物流师','纪实、历史正剧、经典剧情',['纪实','历史','剧情']],ISFJ:['守卫者','温情家庭、日常治愈、轻喜剧',['家庭','治愈','喜剧']],ESTJ:['总经理','动作、警匪、现实主义正剧',['动作','犯罪','现实']],ESFJ:['执政官','爱情喜剧、合家欢、轻快剧情',['爱情','喜剧','家庭']],ISTP:['鉴赏家','动作冒险、硬核格斗、真实事件改编',['动作','冒险','纪实']],ISFP:['探险家','文艺片、音乐片、旅行题材',['文艺','音乐','旅行']],ESTP:['企业家','动作爽片、体育热血、惊悚刺激',['动作','体育','热血','惊悚']],ESFP:['表演者','爆米花喜剧、歌舞片、轻松爱情',['喜剧','音乐','爱情']]};
export const moods={'有点 emo':['治愈','文艺'],'超兴奋':['动作','热血'],'好无聊':['悬疑','喜剧'],'有点焦虑':['喜剧','治愈'],'甜甜的':['爱情'],'想哭一场':['催泪'],'有点愤怒':['动作','热血'],'想笑一下':['喜剧'],'独自安静':['文艺','纪录片'],'想被吓到':['恐怖','惊悚']};
export const allTags=['悬疑','科幻','爱情','喜剧','动作','恐怖','治愈','文艺','奇幻','纪实','热血','催泪','冒险','音乐','纪录片','剧情','家庭','战争','历史','体育','商战','青春'];
export const day=()=>new Date().toLocaleDateString('en-CA');
export function quota(q){return q?.date===day()?q:{date:day(),used:0,bonus:0};}
export function constraints(text=''){const exclude=[],wanted=[];for(const t of allTags){if(new RegExp('(不要|别来|不看|排除|不喜欢)\\s*'+t).test(text))exclude.push(t);else if(text.includes(t))wanted.push(t);}let h=text.match(/(\d+(?:\.\d+)?)\s*(小时|分钟)/);let max=h?Number(h[1])*(h[2]==='小时'?60:1):/两小时|二小时/.test(text)?120:Infinity;const score=text.match(/(?:评分)?\s*(\d(?:\.\d)?)\s*分(?:以上|起)/);return {wanted,exclude,max,min:score?Number(score[1]):/高分/.test(text)?8:0,brain:/别太烧脑|不烧脑|轻松|不要烧脑/.test(text)?2:5};}
export function rank(movies,p){let c=constraints(p.text),profiles=p.couple?[p.profile,p.partner]:[p.profile],black=profiles.flatMap(x=>x.blacklist||[]);let modeTags=p.mode==='mbti'?(mbtis[p.mbti]?.[2]||[]):p.mode==='mood'?(moods[p.mood]||[]):[];return movies.filter(m=>!p.exclude?.includes(m.id)&&!isBlacklisted(m,black)&&m.duration<=c.max&&m.rating>=c.min&&m.brain<=c.brain&&c.wanted.every(t=>m.tags.includes(t))&&!c.exclude.some(t=>m.tags.includes(t))).map(m=>{let likes=profiles.map(x=>[...(x.tags||[]),...(x.actors||[])].filter(t=>[...m.tags,...m.actors].includes(t)));let common=p.couple?likes[0].filter(t=>likes[1].includes(t)).length:0;let hits=likes.flat().length+modeTags.filter(t=>m.tags.includes(t)).length;let score=m.rating*.85+hits*.65+common*.7;return {...m,hits,score,rarity:score>=8.5?'SSR':score>=7.5?'SR':'R',reason:p.mode==='random'?'把选择交给偶然，今晚与这个故事相遇。':`因为你${p.mode==='mbti'?`是 ${p.mbti}`:`今晚${p.mood}`}，为你挑选这部${m.tags.slice(0,2).join(' · ')}作品。${common?'也是你们共同喜欢的类型。':likes.flat().length?'它也命中了你的喜爱标签。':''}`};}).sort((a,b)=>b.score-a.score);}
export function choose(movies,p,rng=Math.random){let pool=rank(movies,p);if(!pool.length)throw Error('没有符合条件的影片，试试调整约束或画像。');return p.mode==='random'?pool[Math.floor(rng()*pool.length)]:pool[0];}
